# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yamdi}
  s.version = "0.1.2"

  s.authors = ["Bob Burbach"]
  s.date = %q{2011-01-28}
  s.description = %q{Yamdi is a ruby wrapper around the command line tool yamdi (github.com/ioppermann/yamdi). You'll need yamdi installed in order for the gem to be of any use. If you are on OSX I recommend using homebrew (brew install yamdi).}
  s.email = %q{bob.burbach@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Changelog.mdown",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/key_frame.rb",
    "lib/paperclip_processors/metadata_extractor.rb",
    "lib/tasks/metadata_refresh.rake",
    "lib/yamdi.rb",
    "spec/files/sample.flv",
    "spec/key_frame_spec.rb",
    "spec/spec_helper.rb",
    "spec/yamdi_spec.rb",
    "yamdi.gemspec"
  ]
  s.homepage = %q{http://github.com/peregrinator/yamdi}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Yamdi is a ruby wrapper around the command line tool yamdi (github.com/ioppermann/yamdi).}
  s.test_files = [
    "spec/key_frame_spec.rb",
    "spec/spec_helper.rb",
    "spec/yamdi_spec.rb"
  ]

  s.add_dependency(%q<nokogiri>, ["~> 1.5.10"])
  s.add_dependency(%q<jeweler>)
end

